CREATE TABLE [dbo].[Talk]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(200) NOT NULL,
	[Start] DATETIME NOT NULL,
	[VenueId] INT NOT NULL,
	CONSTRAINT [FK_Talk_Venue] FOREIGN KEY ([VenueId]) REFERENCES [Venue]([Id])
)
