CREATE TABLE [dbo].[Talk]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(200) NOT NULL,
	[Start] DATETIME NOT NULL,
	[VenueId] INT NOT NULL,
	[Url] NVARCHAR(500) NULL,
	CONSTRAINT [FK_Talk_Venue] FOREIGN KEY ([VenueId]) REFERENCES [Venue]([Id])
)
